language: python

python:
  - "2.7"
  - "3.6"

before_install:
  - echo "INSTALL"
  - sudo bash dependencies.sh
  - virtualenv -p python3.6 .venv

install:
  - echo "INSTALL"
  - .venv/bin/pip install -r requirements.txt

before_script:
  - echo "BEFORE SCRIPT"

script:
  - echo "TODO: SCRIPT HERE"
